# -*- coding: utf-8 -*-
"""Cw_ses4_25BCON1288.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1njCXuPmoJEJV9dOwLu-8vqMG9O9jr-NP

Hello world program
"""

print('hello')

n = int(input('ENTER'))
fact = 1
i= 1
for i in range(n):
  i+=1
  fact = fact*i
print('factorial = ',fact)

def student():
  name=input("enter name")
  rollno = int(input("enter roll"))
  marks = float(input("enter marks"))
  return {'name': name, 'rollno': rollno, 'marks': marks}

